name: Test and Build on PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Placeholder for tests. Uncomment and adapt when have tests.
    # - name: Run Tests
    #   run: |
    #     pip install pytest
    #     pytest

    - name: Build executable with PyInstaller
      run: pyinstaller --name "AI-Commit" --windowed --onefile --icon="assets/icon.ico" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AI-Commit-${{ matrix.os }}
        path: dist/
